### ISSUE TITLE
Amendment needed on 01_better_assertions/05_enums/expectations.yml

### ISSUE THREAD

**Issue by p-alik** [mainmatter/rust-advanced-testing-workshop#5]
Do I see that correctly `expectations.yml` needs an amendment for the test `(01) better_assertions - (05) enums`:
```
$ wr --no-skip
 

Running tests...

	🚀 (01) better_assertions - (00) intro
	🚀 (01) better_assertions - (01) std_assertions
	🚀 (01) better_assertions - (02) googletest
	🚀 (01) better_assertions - (03) eq
	🚀 (01) better_assertions - (04) options_and_results
	❌ (01) better_assertions - (05) enums

	Meditate on your approach and return. Mountains are merely mountains.



Failed to verify expectations.
One or more tests didn't behave as expected
🔘 Checking test `failed_is_b` against expectations
❌ `failed_is_b`
The test failed as expected, but the failure output doesn't match the expected output from `expectations.yml`.

Diff < left / right > :
 Value of: x
<Expected: is MyCustomEnum :: B(_)
>Expected: is MyCustomEnum::B(_)
 Actual: A,
<  which is not MyCustomEnum :: B(_)
>  which is not MyCustomEnum::B(_)

Raw test output:
    thread 'tests::failed_is_b' panicked at exercises/01_better_assertions/05_enums/src/lib.rs:17:9:

    Value of: x
    Expected: is MyCustomEnum :: B(_)
    Actual: A,
      which is not MyCustomEnum :: B(_)
      at exercises/01_better_assertions/05_enums/src/lib.rs:17:9

    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

🔘 Checking test `failed_is_c` against expectations
❌ `failed_is_c`
The test failed as expected, but the failure output doesn't match the expected output from `expectations.yml`.

Diff < left / right > :
 Value of: x
<Expected: is MyCustomEnum :: C { .. }
>Expected: is MyCustomEnum::C { .. }
 Actual: B(10),
<  which is not MyCustomEnum :: C { .. }
>  which is not MyCustomEnum::C { .. }

Raw test output:
    thread 'tests::failed_is_c' panicked at exercises/01_better_assertions/05_enums/src/lib.rs:23:9:

    Value of: x
    Expected: is MyCustomEnum :: C { .. }
    Actual: B(10),
      which is not MyCustomEnum :: C { .. }
      at exercises/01_better_assertions/05_enums/src/lib.rs:23:9


🔘 Checking test `failed_is_c_with_value` against expectations
❌ `failed_is_c_with_value`
The test failed as expected, but the failure output doesn't match the expected output from `expectations.yml`.

Diff < left / right > :
 Value of: x
<Expected: is MyCustomEnum :: C which has field `a`, which is equal to "hello"
>Expected: is MyCustomEnum::C which has field `a`, which is equal to "hello"
 Actual: B(10),
   which has the wrong enum variant `B`

Raw test output:
    thread 'tests::failed_is_c_with_value' panicked at exercises/01_better_assertions/05_enums/src/lib.rs:29:9:

    Value of: x
    Expected: is MyCustomEnum :: C which has field `a`, which is equal to "hello"
    Actual: B(10),
      which has the wrong enum variant `B`
      at exercises/01_better_assertions/05_enums/src/lib.rs:29:9
```

The failure could be resolved by amending `/exercises/01_better_assertions/05_enums/expectations.yml`. `lib.rs` has no differences
```
[apastuchov@ls03064 rust-advanced-testing-workshop (my-solution)]$ git diff origin/solutions -- exercises/01_better_assertions/05_enums
diff --git a/exercises/01_better_assertions/05_enums/expectations.yml b/exercises/01_better_assertions/05_enums/expectations.yml
index 7c6bda1..a21d3fe 100644
--- a/exercises/01_better_assertions/05_enums/expectations.yml
+++ b/exercises/01_better_assertions/05_enums/expectations.yml
@@ -3,20 +3,20 @@ tests:
     expected_outcome: "failure"
     expected_output: |-
       Value of: x
-      Expected: is MyCustomEnum::B(_)
+      Expected: is MyCustomEnum :: B(_)
       Actual: A,
-        which is not MyCustomEnum::B(_)
+        which is not MyCustomEnum :: B(_)
   - name: "failed_is_c"
     expected_outcome: "failure"
     expected_output: |-
       Value of: x
-      Expected: is MyCustomEnum::C { .. }
+      Expected: is MyCustomEnum :: C { .. }
       Actual: B(10),
-        which is not MyCustomEnum::C { .. }
+        which is not MyCustomEnum :: C { .. }
   - name: "failed_is_c_with_value"
     expected_outcome: "failure"
     expected_output: |-
       Value of: x
-      Expected: is MyCustomEnum::C which has field `a`, which is equal to "hello"
+      Expected: is MyCustomEnum :: C which has field `a`, which is equal to "hello"
       Actual: B(10),
-        which has the wrong enum variant `B`
\ No newline at end of file
+        which has the wrong enum variant `B`
```
`(01) better_assertions - (05) enums` succeeded with amended `expectations.yml`
```
$ wr --no-skip
 

Running tests...

	🚀 (01) better_assertions - (00) intro
	🚀 (01) better_assertions - (01) std_assertions
	🚀 (01) better_assertions - (02) googletest
	🚀 (01) better_assertions - (03) eq
	🚀 (01) better_assertions - (04) options_and_results
	🚀 (01) better_assertions - (05) enums
	Eternity lies ahead of us, and behind. Your path is not yet finished. 🍂

Do you want to open the next exercise, (01) better_assertions - (06) collections? [y/n] n
```

**Comment by LukeMathWalker** [comment]
It doesn't look like it—I wasn't able to reproduce the issue you reported on the latest version of `googletest`.
